// 1
// =
// PRASANTHS PROBLEM 1 - [[3,5,6], [3,9,1], [2,0,1,2]] ---> [6,9,2] or,vs code problem

// 2
// =
question:
[
    [
        {
            empId: 1,
            empName: 'veer',
            salary: 1000000
        },
        {
            empId: 2,
            empName: 'pandya',
            salary: 2000000
        },
        {
            empId: 1,
            empName: 'kattabomman',
            salary: 1500000
        },
    ],
    [
        {
            empId: 4,
            empName: 'brahma',
            salary: 1100000
        },
        {
            empId: 5,
            empName: 'saketa',
            salary: 1200000
        },
        {
            empId: 6,
            empName: 'mandan',
            salary: 1300000
        },
    ],
    [
        {
            empId: 7,
            empName: 'etho',
            salary: 1700000
        },
        {
            empId: 8,
            empName: 'oru',
            salary: 1800000
        },
        {
            empId: 9,
            empName: 'lambu',
            salary: 1900000
        },
    ],
];

answer:
[
    [
        {
            empId: 2,
            empName: 'pandya',
            salary: 2000000
        },
    ],
    [
        {
            empId: 6,
            empName: 'mandan',
            salary: 1300000
        },
    ],
    [
        {
            empId: 9,
            empName: 'lambu',
            salary: 1900000
        },
    ]
]